# Libraries:-

In [1]:
import numpy as np

In [2]:
list = np.array([     [[1,2],[1,2]],      [[1,2],[1,2]]    ])

print(list)

[[[1 2]
  [1 2]]

 [[1 2]
  [1 2]]]


In [4]:
arr1 = np.array([1,2,3])

arr2 = np.array([1,2,3])

arr3 = np.array([1,2,3,5,6,7,8,9,10])

arr2D = np.array([[1,2,3],[4,5,6]])

arr3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr1,"\n")

print(arr2,"\n")

print(arr2D,"\n")

print(arr3D,"\n")

[1 2 3] 

[1 2 3] 

[[1 2 3]
 [4 5 6]] 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 



In [5]:
arraySum = arr1 + arr2

arrayDiff = arr1 - arr2

arrayProduct = arr1 * arr2

arrayQuotient = arr1 / arr2 

print(arraySum)

print(arrayDiff)    

print(arrayProduct)

print(arrayQuotient)

[2 4 6]
[0 0 0]
[1 4 9]
[1. 1. 1.]


In [6]:
print(arr1.shape) 

print(arr2D.shape)

print(arr3D.shape) 

print(arr1.ndim) 

print(arr2D.ndim)

print(arr3D.ndim)

(3,)
(2, 3)
(2, 2, 3)
1
2
3


In [7]:
# slicing

print(arr3[0:10:3])

[1 5 8]


In [8]:
import pandas as pd

# vectors - one dimension arrays
data = [2,2,2,3,4,5]

series = pd.Series(data) # index is auto-generated
print(series)

0    2
1    2
2    2
3    3
4    4
5    5
dtype: int64


In [9]:
data = {
    'a': [1,2,3],    
    'b': [4,5,6],
    'c': [7,8,9],
    'd': [10,11,12],
    'e': [13,14,15],
}

df = pd.DataFrame(data) # 
print(df)

   a  b  c   d   e
0  1  4  7  10  13
1  2  5  8  11  14
2  3  6  9  12  15


In [10]:
df.to_csv('data.csv')

In [11]:
df1 = df.drop(columns=['a','b']) # drop columns a and b
print(df1)

   c   d   e
0  7  10  13
1  8  11  14
2  9  12  15


In [12]:
df3 = pd.read_csv('data.csv') # read csv file
print(df3)

   Unnamed: 0  a  b  c   d   e
0           0  1  4  7  10  13
1           1  2  5  8  11  14
2           2  3  6  9  12  15


In [13]:
df1.head()

c   d   e
0  7  10  13
1  8  11  14
2  9  12  15

In [14]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   c       3 non-null      int64
 1   d       3 non-null      int64
 2   e       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes


In [15]:
df1.describe

<bound method NDFrame.describe of    c   d   e
0  7  10  13
1  8  11  14
2  9  12  15>